inputs:
  options:
    description: extra options for config_brpc.sh
    required: false
runs:
  using: "composite"
  steps:
  - run: |
      sudo apt-get update && sudo apt-get install -y clang-12 lldb-12 lld-12 libgtest-dev cmake gdb libstdc++6-11-dbg
    shell: bash
  - run: |
      cd /usr/src/gtest && export CC=clang-12 && export CXX=clang++-12 && sudo cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .
      sudo make -j ${{env.proc_num}} && sudo mv lib/libgtest* /usr/lib/
    shell: bash
  - run: |
      sudo git clone https://github.com/libunwind/libunwind.git
      cd libunwind && sudo git checkout tags/v1.8.1 && sudo mkdir -p /libunwind
      sudo autoreconf -i && sudo CC=clang-12 CXX=clang++-12 ./configure --prefix=/libunwind
      sudo make -j ${{env.proc_num}} && sudo make install
    shell: bash
  - run: |
      sudo git clone https://github.com/gperftools/gperftools.git 
      cd gperftools && sudo git checkout tags/gperftools-2.16 && sudo mkdir -p /gperftools 
      sudo ./autogen.sh && sudo CC=clang-12 CXX=clang++-12 ./configure --prefix=/gperftools --enable-frame-pointers 
      sudo make -j ${{env.proc_num}} && sudo make install
    shell: bash
  - run: |
      sudo git clone https://github.com/abseil/abseil-cpp.git 
      cd abseil-cpp && sudo git checkout lts_2022_06_23 && sudo mkdir -p /abseil-cpp 
      sudo CC=clang-12 CXX=clang++-12 cmake -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=/abseil-cpp -DCMAKE_POLICY_VERSION_MINIMUM=3.5 . 
      sudo make -j ${{env.proc_num}} && sudo sudo make install
    shell: bash
  - run: sh config_brpc.sh --headers="/libunwind/include /gperftools/include /abseil-cpp/include /usr/include" --libs="/libunwind/lib /gperftools/lib /abseil-cpp/lib /usr/lib /usr/lib64" --cc=clang-12 --cxx=clang++-12 ${{inputs.options}} && cat config.mk
    shell: bash
