inputs:
  options:
    description: extra options for config_brpc.sh
    required: false
runs:
  using: "composite"
  steps:
    - run: sh config_brpc.sh --headers=/usr/include --libs=/usr/lib --nodebugsymbols ${{inputs.options}}
      shell: bash
