inputs:
  options:
    description: extra options for config_brpc.sh
    required: false
runs:
  using: "composite"
  steps:
    - run: sh config_brpc.sh --headers="/usr/local/include /usr/include" --libs="/usr/local/lib /usr/local/lib64 /usr/lib /usr/lib64" --nodebugsymbols ${{inputs.options}}
      shell: bash
