name: Runs CMake
description: Runs CMake
inputs:
  compiler:
    description: compiler to run on (either clang or gcc)
    required: false
  extra_options:
    description: indicates if cmake if compiled with extra options (thrift and clanf)
    required: false
runs:
  using: "composite"
  steps:
  - name: Execute the CMake Instructions
    run: |
        if [ "${{inputs.compiler}}" = "clang" ]; then
          export CC=clang && export CXX=clang++
        elif [ "${{inputs.compiler}}" = "gcc" ]; then
          export CC=gcc && export CXX=g++
        fi

        mkdir build
        cd build

        if [ "${{inputs.extra_options}}" = "true" ]; then
          cmake -DWITH_MESALINK=OFF -DWITH_GLOG=ON -DWITH_THRIFT=ON ..
        else
          cmake ..
        fi
    shell: bash
  