PROTOC_EXTRA_ARGS = --plugin=protoc-gen-mcpack=$(BRPC_PATH)/output/bin/protoc-gen-mcpack --proto_path=$(BRPC_PATH)/output/include --proto_path=$(PROTOBUF_HDR) --mcpack_out=. 
include ../echo_c++/Makefile
