#!/bin/bash

LIBS="./output/lib/libbdrpc.a \
    ../../lib2-64/ullib/lib/libullib.a \
    ../../op/oped/noah/webfoot/naming-lib/output/libwebfoot_naming.a \
    ../../public/bthread/libbthread.a \
    ../../public/bvar/libbvar.a \
    ../../public/common/libbase.a \
    ../../public/iobuf/libiobuf.a \
    ../../public/mcpack2pb/libmcpack2pb.a \
    ../../public/noah/giano-lib/release/baas-lib-c/libbaas_interface.a \
    ../../public/protobuf-json/libjson-pb.a \
    ../../third-64/boost/lib/libboost_context.a \
    ../../third-64/gflags/lib/libgflags.a \
    ../../third-64/gflags/lib/libgflags_nothreads.a \
    ../../third-64/gtest/lib/libgmock.a \
    ../../third-64/gtest/lib/libgmock_main.a \
    ../../third-64/gtest/lib/libgtest.a \
    ../../third-64/gtest/lib/libgtest_main.a \
    ../../third-64/libevent/lib/libevent.a \
    ../../third-64/libevent/lib/libevent_core.a \
    ../../third-64/libevent/lib/libevent_extra.a \
    ../../third-64/libevent/lib/libevent_openssl.a \
    ../../third-64/libevent/lib/libevent_pthreads.a \
    ../../third-64/protobuf/lib/libprotobuf-lite.a \
    ../../third-64/protobuf/lib/libprotobuf.a \
    ../../third-64/protobuf/lib/libprotoc.a \
    ../../third-64/tcmalloc/lib/libtcmalloc_and_profiler.a \
    ../../thirdsrc/leveldb/output/lib/libleveldb.a "

INCS="output/include \
  ../../lib2-64/ullib/include \
  ../../op/oped/noah/webfoot/naming-lib/include \
  ../../public/bthread/output/include \
  ../../public/bvar/output/include \
  ../../public/common/output/include \
  ../../public/iobuf/output/include \
  ../../public/mcpack2pb/output/include \
  ../../public/noah/giano-lib/release/baas-lib-c/output/include \
  ../../public/protobuf-json/output/include \
  ../../third-64/boost/include \
  ../../third-64/gflags/include \
  ../../third-64/gtest/include \
  ../../third-64/protobuf/include \
  ../../third-64/tcmalloc/include "

CLOSURE_DIR=baidu_rpc_closure

mkdir -p $CLOSURE_DIR/lib
rm -rf `find $CLOSURE_DIR -name ".svn" -type d`
for lib in $LIBS; do
    cp $lib $CLOSURE_DIR/lib/
done
mkdir -p $CLOSURE_DIR/include
for incdir in $INCS; do
    cp -r $incdir $CLOSURE_DIR
done
rm -rf `find $CLOSURE_DIR -name ".svn" -type d`
cp -f example/multi_threaded_echo_c++/client.cpp $CLOSURE_DIR/client.cpp
cp -f example/multi_threaded_echo_c++/server.cpp $CLOSURE_DIR/server.cpp
cp -f example/multi_threaded_echo_c++/echo.proto $CLOSURE_DIR/echo.proto
cp -f tools/build_closure.mk $CLOSURE_DIR/Makefile
cp -f ../../third-64/protobuf/bin/protoc $CLOSURE_DIR/protoc
